/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnityPC;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Derushan
 */
public class AddUser extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst =null;
    Statement st=null;
    int U_no=0;
    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        try{
                   conn=DBconn.getConn();
                   st= conn.createStatement();
                  
        
        
         }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }
        
        try {
              st=conn.createStatement();
              rs=st.executeQuery("select max(User_ID)from user_details");
           
              rs.next();
              if(rs!=null)
              {
                  U_no=rs.getInt(1);
              U_no++;
              } 
           else
                    U_no=1;
              
             
        
        } catch (Exception ex) {
            Logger.getLogger(addWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("unitypc?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        addproductQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Addproduct a");
        addproductList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : addproductQuery.getResultList();
        userDetails_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM UserDetails_1 u");
        userDetails_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : userDetails_1Query.getResultList();
        jPanel1 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        ChangeButton = new javax.swing.JButton();
        newpasswordtext = new javax.swing.JPasswordField();
        confirmpasswordtext = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ChangeButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(3147, 2147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setBackground(new java.awt.Color(0, 153, 153));
        HomeButton.setFont(new java.awt.Font("Android", 0, 24)); // NOI18N
        HomeButton.setText("Cancel/Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 180, 70));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 110));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Re-Enter New Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 270, 40));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 270, 40));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter New Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 270, 40));

        usernametext.setBackground(new java.awt.Color(255, 153, 51));
        usernametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextActionPerformed(evt);
            }
        });
        jPanel1.add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 230, 40));

        ChangeButton.setBackground(new java.awt.Color(0, 153, 153));
        ChangeButton.setFont(new java.awt.Font("Android", 0, 24)); // NOI18N
        ChangeButton.setText("Add User");
        ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 170, 70));

        newpasswordtext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        newpasswordtext.setForeground(new java.awt.Color(102, 102, 102));
        newpasswordtext.setBorder(null);
        newpasswordtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordtextActionPerformed(evt);
            }
        });
        jPanel1.add(newpasswordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 230, 40));

        confirmpasswordtext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirmpasswordtext.setBorder(null);
        confirmpasswordtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordtextActionPerformed(evt);
            }
        });
        jPanel1.add(confirmpasswordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 230, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, userDetails_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userID}"));
        columnBinding.setColumnName("User ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userName}"));
        columnBinding.setColumnName("User Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${password}"));
        columnBinding.setColumnName("Password");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        ChangeButton1.setBackground(new java.awt.Color(0, 153, 153));
        ChangeButton1.setFont(new java.awt.Font("Android", 0, 24)); // NOI18N
        ChangeButton1.setText("Delete");
        ChangeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ChangeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 170, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        close();
        homeWin h= new homeWin();
        h.setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void usernametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextActionPerformed

    private void ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButtonActionPerformed
        // TODO add your handling code here
        String username = usernametext.getText();
        String newpassword = newpasswordtext.getText();
        String confirmpassword = confirmpasswordtext.getText();

        try{
            
                if( newpassword.equals(confirmpassword) && !newpassword.equals("") &&  !confirmpassword.equals(""))
                {
                    pst=conn.prepareStatement("Insert into user_details values(?,?,?)");
                    pst.setString(2,""+usernametext.getText());
                    pst.setString(3,""+newpasswordtext.getText());
                     try {
                         st=conn.createStatement();
                        rs=st.executeQuery("select max(User_ID)from user_details");
           
                        rs.next();
                    if(rs!=null)
                            {
                            U_no=rs.getInt(1);
                            U_no++;
                            } 
                        else
                        U_no=1;
                    
                pst.setString(2,""+U_no);
                    close();
                    AddUser u =new AddUser();
                            u.setVisible(true);
                
                
        } catch (Exception ex) {
            Logger.getLogger(addWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                    

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"doesnot match with password");

                }
                   }
        catch(SQLException e)
        {
            System.err.println(e);
        }

    }//GEN-LAST:event_ChangeButtonActionPerformed

    private void newpasswordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordtextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_newpasswordtextActionPerformed

    private void confirmpasswordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordtextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_confirmpasswordtextActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
        
            int row =jTable1.getSelectedRow();
            String Table_Click = (jTable1.getModel().getValueAt(row,0).toString());
            String sql12= "select * from user_details where User_ID='"+Table_Click+"'";
            pst= conn.prepareStatement(sql12);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("User_Name");
                usernametext.setText(add1);              
                
            }
            
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ChangeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeButton;
    private javax.swing.JButton ChangeButton1;
    private javax.swing.JButton HomeButton;
    private java.util.List<UnityPC.Addproduct> addproductList;
    private javax.persistence.Query addproductQuery;
    private javax.swing.JPasswordField confirmpasswordtext;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField newpasswordtext;
    private java.util.List<UnityPC.UserDetails_1> userDetails_1List;
    private javax.persistence.Query userDetails_1Query;
    private javax.swing.JTextField usernametext;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
private void close(){
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
}

