/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnityPC;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Derushan
 */
public class addWindow extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst =null;
    Statement st=null;
    int P_no=0;
    /**
     * Creates new form addWindow
     */
   
    //Resize Image 
    /**
     * Creates new form NewJFrame
     */
    public addWindow() {
        initComponents();
         try{
                   conn=DBconn.getConn();
                   st= conn.createStatement();
            }
         catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }
         
         try {
              st=conn.createStatement();
              rs=st.executeQuery("select max(P_ID)from addproduct");
           
              rs.next();
              if(rs!=null)
              {
                  P_no=rs.getInt(1);
              P_no++;
              } 
           else
                    P_no=1;
              
             ID.setText("" + P_no);
        
        } catch (Exception ex) {
            Logger.getLogger(addWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("unitypc?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        addproductQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Addproduct a");
        addproductList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : addproductQuery.getResultList();
        addproductQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Addproduct a");
        addproductList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : addproductQuery1.getResultList();
        addproductQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Addproduct a");
        addproductList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : addproductQuery2.getResultList();
        addproductQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Addproduct a");
        addproductList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : addproductQuery3.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Months = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SerialNo = new javax.swing.JTextField();
        Categorylist = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ModelName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        Make = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(3147, 2147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton2.setFont(new java.awt.Font("Arno Pro Smbd SmText", 0, 20)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(875, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 110));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serial No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 90, 30));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Brand Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 120, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 50, 30));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 90, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 90, 30));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, 33));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, 33));

        Months.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MonthsKeyReleased(evt);
            }
        });
        jPanel1.add(Months, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 130, 33));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 33));

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 80, 30));

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 60, 30));

        datechooser.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 30));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Catagory :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 30));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 30, 30));

        SerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialNoActionPerformed(evt);
            }
        });
        SerialNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SerialNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SerialNoKeyTyped(evt);
            }
        });
        jPanel1.add(SerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, 33));

        Categorylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptops", "Computer Casing", "UPS", "Power Supply", "Motherboard", "Expansion Cards", "MOUSE", "KEYBOARD", "Harddisk", "DVD/CD writer", "AUDIO Item", "Projector", "Monitor", "Storage Devices", " ", " " }));
        Categorylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorylistActionPerformed(evt);
            }
        });
        Categorylist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CategorylistKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CategorylistKeyReleased(evt);
            }
        });
        jPanel1.add(Categorylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 130, 30));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, addproductList3, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PId}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PSerialNO}"));
        columnBinding.setColumnName("Serial NO");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PCategory}"));
        columnBinding.setColumnName("Category");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PMake}"));
        columnBinding.setColumnName("Make");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PType}"));
        columnBinding.setColumnName("Type");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PModelName}"));
        columnBinding.setColumnName("Model Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PName}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PPrice}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PAddDate}"));
        columnBinding.setColumnName("Add Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PQunatity}"));
        columnBinding.setColumnName("Qunatity");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${PAddWarMonth}"));
        columnBinding.setColumnName(" Warranty Month");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 690, 500));

        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantityKeyReleased(evt);
            }
        });
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 130, 33));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Waranty Months:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 150, 30));

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, 30));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Make :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, 30));

        ModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelNameActionPerformed(evt);
            }
        });
        jPanel1.add(ModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, 33));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Type :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 60, 30));

        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        jPanel1.add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, 33));

        Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeActionPerformed(evt);
            }
        });
        jPanel1.add(Make, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 33));

        jLabel21.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Model:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(3147, 2147));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        homeWin h= new homeWin();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_IDActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        name.setText("");
        SerialNo.setText("");
        Quantity.setText("");
        price.setText("");
        Months.setText("");
        ModelName.setText("");
        Make.setText("");
        Type.setText("");
        //conn.close();
        conn=DBconn.getConn();

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        try
        {

            pst=conn.prepareStatement("Insert into addproduct values(?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,""+ID.getText());
            pst.setString(2,""+SerialNo.getText());
            String value= Categorylist.getSelectedItem().toString();
            pst.setString(3,""+value);
            pst.setString(4,""+name.getText());
            pst.setString(5,""+price.getText());
            pst.setString(6,""+((JTextField)datechooser.getDateEditor().getUiComponent()).getText());
            pst.setString(7,""+Quantity.getText());
            pst.setString(8,""+Months.getText());
            pst.setString(9,""+ModelName.getText());
            pst.setString(10,""+Make.getText());
            pst.setString(11,""+Type.getText());
            

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Inserted Sucessfully....");
            rs=st.executeQuery("select max(P_ID)from addproduct");

            rs.next();
            if(rs!=null)
            {
                P_no=rs.getInt(1);
                P_no++;
            }
            else
                P_no=1;

            ID.setText(""+P_no);

            name.setText("");
            price.setText("");
            
            Months.setText("");
            
            close();
            addWindow h= new addWindow();
        h.setVisible(true);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);;
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void SerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialNoActionPerformed
        // TODO add your handling code here:
          String value= Categorylist.getSelectedItem().toString();
        
        switch(value)
        {
            case "Laptops":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "Computer Casing":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "UPS":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "Power Supply":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "Motherboard":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "Expansion Cards":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "MOUSE":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "KEYBOARD":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            case "Harddisk":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break; 
            case "DVD/CD writer":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break; 
            case "AUDIO Item":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break; 
            case "Projector":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break; 
            case "Monitor":
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
            default:
                SerialNo.setDocument(new JTextFieldLimit(8));
                break;
                
        
        }
//       String value= Categorylist.getSelectedItem().toString();
//        switch(value){
//           
//            case 'Laptops' :
//                
//       
//       
//       
//       } 
       
    }//GEN-LAST:event_SerialNoActionPerformed

    private void CategorylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorylistActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        try{
        
            int row =jTable2.getSelectedRow();
            String Table_Click = (jTable2.getModel().getValueAt(row,0).toString());
            String sql12= "select * from addproduct where P_ID='"+Table_Click+"'";
            pst= conn.prepareStatement(sql12);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("P_ID");
                ID.setText(add1);
                String add2=rs.getString("P_SerialNo");
                SerialNo.setText(add2);
                String add3=rs.getString("P_Category");
                Categorylist.addItem(add3);
                String add4=rs.getString("P_Name");
                name.setText(add4);
                String add5=rs.getString("P_Price");
                price.setText(add5);
                Date add6=rs.getDate("P_AddDate");
                datechooser.setDate(add6);
                String add7=rs.getString("P_Qunatity");
                Quantity.setText(add7);
                String add8=rs.getString("P_AddWarMonth");
                Months.setText(add8);
                String add9=rs.getString("P_ModelName");
                ModelName.setText(add9);
                String add10=rs.getString("P_Make");
                ModelName.setText(add10);
                String add11=rs.getString("P_Type");
                ModelName.setText(add11);
            }
            
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         try
        {
            
            String value1=ID.getText();
            String value2=SerialNo.getText();
            String value3= Categorylist.getSelectedItem().toString();
            String value4=name.getText();
            String value5=price.getText();
            java.util.Date value6=datechooser.getDate();
            String value7=Quantity.getText();
            String value8=Months.getText();
            String value9=ModelName.getText();
            String value10=Make.getText();
            String value11=Type.getText();
            
            pst=conn.prepareStatement("update addproduct set P_ID='"+value1+"', P_SerialNo='"+value2+"', P_Category='"+value3+"' , P_Name='"+value4+"' , P_Price='"+value5+"' ,  P_Qunatity='"+value7+"' , P_AddWarMonth = '"+value8+"',P_ModelName='"+value9+"' , P_Make='"+value10+"', P_Type='"+value11+"' where P_ID='"+value1+"' ");
        
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Upadated Sucessfully....");
            rs=st.executeQuery("select max(P_ID)from addproduct");

            rs.next();
            if(rs!=null)
            {
                P_no=rs.getInt(1);
                P_no++;
            }
            else
            P_no=1;

            ID.setText(""+P_no);

            name.setText("");
            price.setText("");
            
            Months.setText("");
            
            close();
            addWindow h= new addWindow();
        h.setVisible(true);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);;
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void ModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNameActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        // TODO add your handling code here:
    int f=0; 
    String s=price.getText();
    String s1=null;
    for(int i=0;i<s.length();i++)
    {
      char a=s.charAt(i);  
       Character chr=new Character(a);
       
      if(chr.isLetter(a))
      {
           f=1;
        s1=s.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
     price.setText(null);
    }
    }//GEN-LAST:event_priceKeyReleased

    private void SerialNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SerialNoKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SerialNoKeyReleased

    private void CategorylistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CategorylistKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CategorylistKeyReleased

    private void SerialNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SerialNoKeyTyped
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_SerialNoKeyTyped

    private void QuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyReleased
        // TODO add your handling code here:
        
        int f=0; 
    String s=Quantity.getText();
    String s1=null;
    for(int i=0;i<s.length();i++)
    {
      char a=s.charAt(i);  
       Character chr=new Character(a);
       
      if(chr.isLetter(a))
      {
           f=1;
        s1=s.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
     Quantity.setText(null);
    }
    }//GEN-LAST:event_QuantityKeyReleased

    private void MonthsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonthsKeyReleased

        // TODO add your handling code here:
          int f=0; 
    String s=Months.getText();
    String s1=null;
    for(int i=0;i<s.length();i++)
    {
      char a=s.charAt(i);  
       Character chr=new Character(a);
       
      if(chr.isLetter(a))
      {
           f=1;
        s1=s.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
     Months.setText(null);
    }
    }//GEN-LAST:event_MonthsKeyReleased

    private void CategorylistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CategorylistKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorylistKeyPressed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> Categorylist;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Make;
    private javax.swing.JTextField ModelName;
    private javax.swing.JTextField Months;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField SerialNo;
    private javax.swing.JTextField Type;
    private javax.swing.JButton Update;
    private java.util.List<UnityPC.Addproduct> addproductList;
    private java.util.List<UnityPC.Addproduct> addproductList1;
    private java.util.List<UnityPC.Addproduct> addproductList2;
    private java.util.List<UnityPC.Addproduct> addproductList3;
    private javax.persistence.Query addproductQuery;
    private javax.persistence.Query addproductQuery1;
    private javax.persistence.Query addproductQuery2;
    private javax.persistence.Query addproductQuery3;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
private void close(){
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
}
