/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnityPC;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Derushan
 */
public class SearchProduct extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst =null;
    Statement st=null;
    DefaultTableModel  dml;
     
     private Vector<Vector<String>> data;
        private Vector<String> header;
    /**
     * Creates new form SearchProduct
     */
    public SearchProduct(){
        initComponents();
        try{
                   conn=DBconn.getConn();
                   st= conn.createStatement();
            }
         catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }
       
        try{
            DCEngin dce = new DCEngin("select * from addproduct");
        
       data = dce.getData();
       
       header = new Vector<String>();
            header.add("Product ID");
            header.add("Serial No");
            header.add("Catageroy");
            header.add("Make");
            header.add("Type");
            header.add("Model");
            header.add("Name");
            header.add("Price");
            header.add("AddDate");
            header.add("Quantity");
            header.add("Warranty Month");
        }
        catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Valuebox = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Make = new javax.swing.JComboBox<>();
        Type = new javax.swing.JComboBox<>();
        Model = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(3147, 2147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton2.setFont(new java.awt.Font("Arno Pro Smbd SmText", 0, 20)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(912, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 110));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, 20));

        Valuebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueboxActionPerformed(evt);
            }
        });
        jPanel1.add(Valuebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, 30));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 130, 30));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, searchbutton, org.jdesktop.beansbinding.ObjectProperty.create(), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 170, 950, 280));

        jLabel1.setText("Category");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 60, 20));

        jLabel3.setText("Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 40, 20));

        jLabel4.setText("Model");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 40, 20));

        Category.setEditable(true);
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Computer Casing", "UPS", "Power Supply", "Motherboard", "Expansion Cards", "MOUSE", "KEYBOARD", "Harddisk", "DVD/CD writer", "AUDIO Item", "Projector", "Monitor", "Storage Devices", " ", " " }));
        jPanel1.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, 30));

        jLabel5.setText("Make");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 40, 20));

        jLabel6.setText("Serial No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, 20));

        Make.setEditable(true);
        Make.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HP", "Dell", "Toshiba", "Lenovo", "Gigabyte", "Intel", "Asus" }));
        jPanel1.add(Make, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 100, 30));

        Type.setEditable(true);
        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HP", "Dell", "Toshiba", "Lenovo", "Gigabyte", "Intel", "Asus" }));
        jPanel1.add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 100, 30));

        Model.setEditable(true);
        Model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HP", "Dell", "Toshiba", "Lenovo", "Gigabyte", "Intel", "Asus" }));
        jPanel1.add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValueboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueboxActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
           
            String value1=Valuebox.getText();
            String value2=Category.getSelectedItem().toString(); 
            String value3=Make.getSelectedItem().toString();
            String value4=Type.getSelectedItem().toString();
            String value5=Model.getSelectedItem().toString();

                try {
                 DCEngin dce = new DCEngin("select * from addproduct where (P_SerialNo  like '"+value1+"%') AND (P_Category like '"+value2+"%') AND (P_Make like '"+value3+"%') AND (P_Type like '"+value4+"%') AND (P_ModelName like '"+value5+"%')");
                 data = dce.getData();
                 
                 header = new Vector<String>();
                    header.add("Product ID");
                    header.add("Serial No");
                    header.add("Category");
                    header.add("Make");
                    header.add("Type");
                    header.add("Model");
                    header.add("Name");
                    header.add("Price");
                    header.add("AddDate");
                    header.add("Quantity");
                    header.add("Warranty Month");
       
                        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));           
                            } catch (Exception ex) {
                                Logger.getLogger(SearchProduct.class.getName()).log(Level.SEVERE, null, ex);
                            }
           
            
            
         
        
       
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        homeWin h= new homeWin();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new SearchProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JComboBox<String> Make;
    private javax.swing.JComboBox<String> Model;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JTextField Valuebox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchbutton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
private void close(){
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
}
